// <auto-generated />
using System;
using ECOM.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECOM.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260316123833_AddressSeedData")]
    partial class AddressSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ECOM.API.Data.Entities.EmailVerification", b =>
                {
                    b.Property<int>("VerificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VerificationId"));

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CODE_HASH");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("EXPIRED_AT");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit")
                        .HasColumnName("IS_USED");

                    b.HasKey("VerificationId");

                    b.ToTable("EMAIL_VERIFICATION", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Addresses", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS");

                    b.Property<string>("AddressName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ADDRESS_NAME");

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CITY_ID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("DISTRICT_ID");

                    b.Property<int>("NeighbourhoodId")
                        .HasColumnType("int")
                        .HasColumnName("NEIGHBOURHOOD_ID");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int")
                        .HasColumnName("RECEIVER_ID");

                    b.HasKey("AddressId");

                    b.HasIndex("CityId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NeighbourhoodId");

                    b.HasIndex("ReceiverId");

                    b.ToTable("ADDRESSES", (string)null);

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            AdditionTime = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "Moda Cad. No:12 D:3",
                            AddressName = "Ev",
                            CityId = 1,
                            CustomerId = 1,
                            DistrictId = 1,
                            NeighbourhoodId = 1,
                            ReceiverId = 1
                        },
                        new
                        {
                            AddressId = 2,
                            AdditionTime = new DateTime(2024, 2, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "Levent Mah. Büyükdere Cad. No:45 Kat:7",
                            AddressName = "İş yeri",
                            CityId = 1,
                            CustomerId = 1,
                            DistrictId = 2,
                            NeighbourhoodId = 3,
                            ReceiverId = 1
                        },
                        new
                        {
                            AddressId = 3,
                            AdditionTime = new DateTime(2024, 3, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "Fenerbahçe Mah. Bağdat Cad. No:78",
                            AddressName = "Ev",
                            CityId = 1,
                            CustomerId = 2,
                            DistrictId = 1,
                            NeighbourhoodId = 2,
                            ReceiverId = 2
                        },
                        new
                        {
                            AddressId = 4,
                            AdditionTime = new DateTime(2024, 4, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "Etiler Mah. Nisbetiye Cad. No:5 D:8",
                            AddressName = "Annem",
                            CityId = 1,
                            CustomerId = 2,
                            DistrictId = 2,
                            NeighbourhoodId = 4,
                            ReceiverId = 3
                        },
                        new
                        {
                            AddressId = 5,
                            AdditionTime = new DateTime(2024, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Address = "Kızılay Mah. Atatürk Bulvarı No:101 D:2",
                            AddressName = "Ev",
                            CityId = 2,
                            CustomerId = 3,
                            DistrictId = 4,
                            NeighbourhoodId = 5,
                            ReceiverId = 3
                        });
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("BrandId");

                    b.ToTable("BRANDS", (string)null);

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Samsung"
                        },
                        new
                        {
                            BrandId = 2,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Apple"
                        },
                        new
                        {
                            BrandId = 3,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Sony"
                        },
                        new
                        {
                            BrandId = 4,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "LG"
                        },
                        new
                        {
                            BrandId = 5,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Xiaomi"
                        });
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CardId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<string>("CVV")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CVV");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("CARD_NO");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("ExpirationDate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CardId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CARDS", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CartId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<int?>("DCouponId")
                        .HasColumnType("int")
                        .HasColumnName("DCOUPON_ID");

                    b.Property<bool?>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("ENABLE");

                    b.Property<int?>("Piece")
                        .HasColumnType("int")
                        .HasColumnName("PIECE");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("SELLER_ID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TOTAL_PRICE");

                    b.HasKey("CartId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DCouponId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("CART", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("CityId");

                    b.ToTable("CITY", (string)null);

                    b.HasData(
                        new
                        {
                            CityId = 1,
                            Name = "İstanbul"
                        },
                        new
                        {
                            CityId = 2,
                            Name = "Ankara"
                        },
                        new
                        {
                            CityId = 3,
                            Name = "İzmir"
                        });
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Comments", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("COMMENT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMAGE_PATH");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int?>("Score")
                        .HasColumnType("int")
                        .HasColumnName("SCORE");

                    b.HasKey("CommentId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("COMMENTS", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Customers", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("BIRTHDATE");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EMAIL");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit")
                        .HasColumnName("GENDER");

                    b.Property<bool?>("IsCustomer")
                        .HasColumnType("bit")
                        .HasColumnName("IS_CUSTOMER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PASSWORD");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PHONE");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("SURNAME");

                    b.HasKey("CustomerId");

                    b.ToTable("CUSTOMERS", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.DCoupon", b =>
                {
                    b.Property<int>("DCouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DCouponId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime?>("DefinitionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DEFINITION_DATE");

                    b.Property<bool?>("Enable")
                        .HasColumnType("bit")
                        .HasColumnName("ENABLE");

                    b.Property<int>("SCouponId")
                        .HasColumnType("int")
                        .HasColumnName("S_COUPON_ID");

                    b.HasKey("DCouponId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SCouponId");

                    b.ToTable("D_COUPONS", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.District", b =>
                {
                    b.Property<int>("DistrictId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DistrictId"));

                    b.Property<int>("CityId")
                        .HasColumnType("int")
                        .HasColumnName("CITY_ID");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("DistrictId");

                    b.HasIndex("CityId");

                    b.ToTable("DISTRICT", (string)null);

                    b.HasData(
                        new
                        {
                            DistrictId = 1,
                            CityId = 1,
                            Name = "Kadıköy"
                        },
                        new
                        {
                            DistrictId = 2,
                            CityId = 1,
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            DistrictId = 3,
                            CityId = 1,
                            Name = "Üsküdar"
                        },
                        new
                        {
                            DistrictId = 4,
                            CityId = 2,
                            Name = "Çankaya"
                        },
                        new
                        {
                            DistrictId = 5,
                            CityId = 3,
                            Name = "Konak"
                        });
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Favorites", b =>
                {
                    b.Property<int>("FavoriteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoriteId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.HasKey("FavoriteId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("FAVORITES", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Log", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NEW_VALUE");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OLD_VALUE");

                    b.Property<DateTime?>("ProcessTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("PROCESS_TIME");

                    b.Property<string>("ProcessType")
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("PROCESS_TYPE");

                    b.Property<string>("TableName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("TABLE_NAME");

                    b.HasKey("LogId");

                    b.ToTable("LOG", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Neighbourhood", b =>
                {
                    b.Property<int>("NeighbourhoodId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NeighbourhoodId"));

                    b.Property<int?>("CityId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int")
                        .HasColumnName("DISTRICT_ID");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.HasKey("NeighbourhoodId");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("NEIGHBOURHOODS", (string)null);

                    b.HasData(
                        new
                        {
                            NeighbourhoodId = 1,
                            DistrictId = 1,
                            Name = "Moda"
                        },
                        new
                        {
                            NeighbourhoodId = 2,
                            DistrictId = 1,
                            Name = "Göztepe"
                        },
                        new
                        {
                            NeighbourhoodId = 3,
                            DistrictId = 2,
                            Name = "Levent"
                        },
                        new
                        {
                            NeighbourhoodId = 4,
                            DistrictId = 2,
                            Name = "Etiler"
                        },
                        new
                        {
                            NeighbourhoodId = 5,
                            DistrictId = 4,
                            Name = "Kızılay"
                        });
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.OrderHistory", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("CardId")
                        .HasColumnType("int")
                        .HasColumnName("CARD_ID");

                    b.Property<int?>("CartId")
                        .HasColumnType("int")
                        .HasColumnName("CART_ID");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int")
                        .HasColumnName("CUSTOMER_ID");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("DELIVERY_DATE");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ORDER_DATE");

                    b.Property<int?>("Piece")
                        .HasColumnType("int")
                        .HasColumnName("PIECE");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("PRODUCT_ID");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("SELLER_ID");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TOTAL_PRICE");

                    b.HasKey("OrderId");

                    b.HasIndex("CardId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SellerId");

                    b.ToTable("ORDER_HISTORY", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<int>("BrandId")
                        .HasColumnType("int")
                        .HasColumnName("BRAND_ID");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("IMAGE_PATH");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PRICE");

                    b.Property<float?>("Score")
                        .HasColumnType("real")
                        .HasColumnName("SCORE");

                    b.Property<int>("SellerId")
                        .HasColumnType("int")
                        .HasColumnName("SELLER_ID");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("SUB_CATEGORY_ID");

                    b.Property<int>("SupCategoryId")
                        .HasColumnType("int")
                        .HasColumnName("SUP_CATEGORY_ID");

                    b.HasKey("ProductId");

                    b.HasIndex("BrandId");

                    b.HasIndex("SellerId");

                    b.HasIndex("SubCategoryId");

                    b.HasIndex("SupCategoryId");

                    b.ToTable("PRODUCTS", (string)null);

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            AdditionTime = new DateTime(2024, 9, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 2,
                            Description = "A17 Pro çip, 48MP kamera sistemi ve titanyum tasarım ile güçlü bir akıllı telefon.",
                            ImagePath = "/images/products/iphone15pro.jpg",
                            Name = "Apple iPhone 15 Pro",
                            Price = 54999.99m,
                            Score = 4.8f,
                            SellerId = 1,
                            SubCategoryId = 2,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 2,
                            AdditionTime = new DateTime(2024, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 1,
                            Description = "Snapdragon 8 Gen 3 işlemci, 200MP kamera ve dahili S Pen ile üst segment deneyimi.",
                            ImagePath = "/images/products/s24ultra.jpg",
                            Name = "Samsung Galaxy S24 Ultra",
                            Price = 49999.99m,
                            Score = 4.7f,
                            SellerId = 2,
                            SubCategoryId = 2,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 3,
                            AdditionTime = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 5,
                            Description = "Leica kamera ortaklığı, 5000mAh batarya ve 144Hz AMOLED ekran.",
                            ImagePath = "/images/products/xiaomi14tpro.jpg",
                            Name = "Xiaomi 14T Pro",
                            Price = 24999.99m,
                            Score = 4.5f,
                            SellerId = 3,
                            SubCategoryId = 2,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 4,
                            AdditionTime = new DateTime(2024, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 2,
                            Description = "M3 çip, 13.6 inç Liquid Retina ekran ve 18 saate kadar pil ömrü.",
                            ImagePath = "/images/products/macbookairm3.jpg",
                            Name = "Apple MacBook Air M3",
                            Price = 44999.99m,
                            Score = 4.9f,
                            SellerId = 1,
                            SubCategoryId = 3,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 5,
                            AdditionTime = new DateTime(2024, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 1,
                            Description = "Intel Core Ultra 7 işlemci, 14 inç AMOLED ekran ve hafif alüminyum gövde.",
                            ImagePath = "/images/products/galaxybook4pro.jpg",
                            Name = "Samsung Galaxy Book4 Pro",
                            Price = 38999.99m,
                            Score = 4.4f,
                            SellerId = 2,
                            SubCategoryId = 3,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 6,
                            AdditionTime = new DateTime(2024, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 1,
                            Description = "Neo Quantum işlemci, Mini LED arka aydınlatma ve Dolby Atmos ses desteği.",
                            ImagePath = "/images/products/samsungneqled65.jpg",
                            Name = "Samsung Neo QLED 4K 65\"",
                            Price = 34999.99m,
                            Score = 4.6f,
                            SellerId = 3,
                            SubCategoryId = 4,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 7,
                            AdditionTime = new DateTime(2024, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 4,
                            Description = "OLED evo panel, α9 AI işlemci ve webOS 24 ile sinema kalitesi deneyim.",
                            ImagePath = "/images/products/lgoled c4.jpg",
                            Name = "LG OLED C4 55\"",
                            Price = 29999.99m,
                            Score = 4.8f,
                            SellerId = 1,
                            SubCategoryId = 4,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 8,
                            AdditionTime = new DateTime(2023, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 3,
                            Description = "Sektörün en iyi gürültü engelleme teknolojisi, 30 saat pil ömrü ve katlanabilir tasarım.",
                            ImagePath = "/images/products/sonywh1000xm5.jpg",
                            Name = "Sony WH-1000XM5",
                            Price = 9999.99m,
                            Score = 4.9f,
                            SellerId = 2,
                            SubCategoryId = 5,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 9,
                            AdditionTime = new DateTime(2023, 9, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 2,
                            Description = "Aktif gürültü engelleme, Adaptif Ses ve H2 çip ile mükemmel ses deneyimi.",
                            ImagePath = "/images/products/airpodspro2.jpg",
                            Name = "Apple AirPods Pro 2",
                            Price = 8499.99m,
                            Score = 4.7f,
                            SellerId = 3,
                            SubCategoryId = 5,
                            SupCategoryId = 1
                        },
                        new
                        {
                            ProductId = 10,
                            AdditionTime = new DateTime(2024, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            BrandId = 5,
                            Description = "OLED ekran, HEPA filtre ve Mi Home uygulaması ile akıllı hava temizleyici.",
                            ImagePath = "/images/products/xiaomipurifier4pro.jpg",
                            Name = "Xiaomi Smart Air Purifier 4 Pro",
                            Price = 3499.99m,
                            Score = 4.3f,
                            SellerId = 1,
                            SubCategoryId = 6,
                            SupCategoryId = 1
                        });
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.ProductCategories", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<bool>("Type")
                        .HasColumnType("bit")
                        .HasColumnName("TYPE");

                    b.HasKey("CategoryId");

                    b.ToTable("PRODUCT_CATEGORIES", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Elektronik",
                            Type = false
                        },
                        new
                        {
                            CategoryId = 2,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Telefon",
                            Type = false
                        },
                        new
                        {
                            CategoryId = 3,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Bilgisayar",
                            Type = false
                        },
                        new
                        {
                            CategoryId = 4,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Televizyon",
                            Type = false
                        },
                        new
                        {
                            CategoryId = 5,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ses Sistemleri",
                            Type = false
                        },
                        new
                        {
                            CategoryId = 6,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Küçük Ev Aletleri",
                            Type = false
                        });
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.SCoupon", b =>
                {
                    b.Property<int>("SCouponId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SCouponId"));

                    b.Property<decimal?>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("AMOUNT");

                    b.Property<decimal?>("LowerLimit")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("LOWER_LIMIT");

                    b.Property<DateTime?>("ValidityDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("VALIDITY_DATE");

                    b.HasKey("SCouponId");

                    b.ToTable("S_COUPONS", (string)null);
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Seller", b =>
                {
                    b.Property<int>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SellerId"));

                    b.Property<DateTime?>("AdditionTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("ADDITION_TIME");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("NAME");

                    b.Property<float?>("Score")
                        .HasColumnType("real")
                        .HasColumnName("SCORE");

                    b.HasKey("SellerId");

                    b.ToTable("SELLERS", (string)null);

                    b.HasData(
                        new
                        {
                            SellerId = 1,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "TechStore"
                        },
                        new
                        {
                            SellerId = 2,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "ElektroMarket"
                        },
                        new
                        {
                            SellerId = 3,
                            AdditionTime = new DateTime(2023, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "DigiShop"
                        });
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Addresses", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.City", "City")
                        .WithMany("CityOfAddresses")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Customers", "Customer")
                        .WithMany("CustomerAddresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.District", "District")
                        .WithMany("DistrictOfAddresses")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Neighbourhood", "Neighbourhood")
                        .WithMany("NeighbourhoodOfAddresss")
                        .HasForeignKey("NeighbourhoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Customers", "Receiver")
                        .WithMany("ReceiverAddresses")
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Customer");

                    b.Navigation("District");

                    b.Navigation("Neighbourhood");

                    b.Navigation("Receiver");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Card", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.Customers", "Customer")
                        .WithMany("Cards")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Cart", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.Customers", "Customer")
                        .WithMany("Carts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.DCoupon", "Coupon")
                        .WithMany("Carts")
                        .HasForeignKey("DCouponId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ECOM.Api.Data.Entities.Product", "Product")
                        .WithMany("Carts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Seller", "Seller")
                        .WithMany("Carts")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Comments", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.Customers", "Customer")
                        .WithMany("Comments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Product", "Product")
                        .WithMany("Comments")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.DCoupon", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.Customers", "Customer")
                        .WithMany("Coupons")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.SCoupon", "Coupon")
                        .WithMany("Coupons")
                        .HasForeignKey("SCouponId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coupon");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.District", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Favorites", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.Customers", "Customer")
                        .WithMany("Favorites")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Product", "Product")
                        .WithMany("Favorites")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Neighbourhood", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.City", null)
                        .WithMany("Neighbourhoods")
                        .HasForeignKey("CityId");

                    b.HasOne("ECOM.Api.Data.Entities.District", "District")
                        .WithMany("Neighbourhoods")
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.OrderHistory", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.Card", "Card")
                        .WithMany("Orders")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ECOM.Api.Data.Entities.Customers", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Product", "Product")
                        .WithMany("Orders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Seller", "Seller")
                        .WithMany("Orders")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Customer");

                    b.Navigation("Product");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Product", b =>
                {
                    b.HasOne("ECOM.Api.Data.Entities.Brand", "Brand")
                        .WithMany("Products")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.Seller", "Seller")
                        .WithMany("Products")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.ProductCategories", "SubCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECOM.Api.Data.Entities.ProductCategories", "SupCategory")
                        .WithMany("SupCategories")
                        .HasForeignKey("SupCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Seller");

                    b.Navigation("SubCategory");

                    b.Navigation("SupCategory");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Brand", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Card", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.City", b =>
                {
                    b.Navigation("CityOfAddresses");

                    b.Navigation("Districts");

                    b.Navigation("Neighbourhoods");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Customers", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Carts");

                    b.Navigation("Comments");

                    b.Navigation("Coupons");

                    b.Navigation("CustomerAddresses");

                    b.Navigation("Favorites");

                    b.Navigation("Orders");

                    b.Navigation("ReceiverAddresses");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.DCoupon", b =>
                {
                    b.Navigation("Carts");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.District", b =>
                {
                    b.Navigation("DistrictOfAddresses");

                    b.Navigation("Neighbourhoods");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Neighbourhood", b =>
                {
                    b.Navigation("NeighbourhoodOfAddresss");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Product", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Comments");

                    b.Navigation("Favorites");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.ProductCategories", b =>
                {
                    b.Navigation("SubCategories");

                    b.Navigation("SupCategories");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.SCoupon", b =>
                {
                    b.Navigation("Coupons");
                });

            modelBuilder.Entity("ECOM.Api.Data.Entities.Seller", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Orders");

                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
